# Generated by Django 3.2.7 on 2021-09-17 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Createprofile', '0002_auto_20210916_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.FileField(default='not found', upload_to='documents/'),
            preserve_default=False,
        ),
    ]
