# Generated by Django 3.2.7 on 2021-09-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Createprofile', '0003_userprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
